VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# Require 'yaml' module
require 'yaml'

containers = YAML.load_file('containers.yml')

# Create and configure the Docker container(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.provider "docker" do |docker|
  #   docker.vagrant_vagrantfile = "host/Vagrantfile"
  # end

  # Iterate through the entries in the YAML file
  containers.each do |container|
    config.vm.define container["name"] do |cntnr|
      # cntnr.vm.synced_folder ".", "/vagrant", disabled: true
      # Configure the Docker provider for Vagrant
      cntnr.vm.provider "docker" do |docker, override|
        docker.build_dir = "."
        override.ssh.insert_key = true
        docker.has_ssh = true
        docker.privileged = true
        # docker.image = container["image"]
        # docker.ports = container["ports"]
        docker.name = container["name"]
      end
    end
  end
end